version: '3'
services:
  python-app:    
    build: .
    environment:
      KAFKA_BROKER_URL: kafka_server:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 1000

networks:
  default:
    external:
      name: kafka-network 